version: '3.7'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./wordpress/wp-content:/srv/www/content
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
  wordpress:
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "4000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpassword
      WORDPRESS_DB_NAME: wordpress
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "5000:80"
    restart: always
    environment:
      PMA_HOST: db:3306
volumes:
db_data: {}